language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode8.3


    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty

    - os: windows


install:
  - cd ${TRAVIS_BUILD_DIR}
  - |
    mkdir -p build
    cd build
    cmake ..
  - make -j4

script:
  - ./../run