language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
    - os: osx
      osx_image: xcode10.3

    - os: linux
      dist: bionic
    - os: linux
      dist: xenial

    - os: windows


install:
  - |
    cd ${TRAVIS_BUILD_DIR}
    mkdir -p build
    cd build
  - cmake ..
  - cmake --build . -j 4

script:
  - ./../run